name: "Test"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm ci
      - run: npm run build
      - run: npm test

  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm ci
      - run: npm run lint

  Example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: npm ci
      - run: npm run build
      - run: npm --prefix example install
      - run: npm --prefix example run build
